version: '3'

services:
  sshtunnel:
    image: ghcr.io/frysee/sshtunnel
    container_name: sshtunnel
    restart: unless-stopped
    volumes:
      - ./sshconfig:/root/ssh:ro
    ports:
      - 8081:8081
