version: '3'

services:
  sshtunnel:
    image: frysee/sshtunnel
    container_name: sshtunnel
    volumes:
      - ./config:/root/.ssh:ro
    environment:
      - TUNNEL_HOST=host.example.com
      - TUNNEL_PORT=22
      - REMOTE_HOST=localhost
      - LOCAL_PORT=2525
      - REMOTE_PORT=25
      - KEY=/data/keyfile
    restart: always